# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.13 # Use the Node version that matches your environment
    steps:
      - checkout
      - run: npm install
      - run: npm run test # Make sure you have a test script in your package.json

workflows:
  version: 2
  build:
    jobs:
      - build
